# Generated by @coding-with-hassan/devkit — do not edit by hand.
# Re-run `hassan-devkit hooks:install` to refresh after a devkit bump.

# 1. Project-specific guards (optional seam: scripts/pre-commit-extra.sh, must exit 0)
if [ -f "scripts/pre-commit-extra.sh" ]; then
  sh scripts/pre-commit-extra.sh || exit 1
fi

# 2. Translation keys for flat projects (no-op when hassan-devkit.i18n is not configured
#    and the default dir does not exist; Nx monorepos enforce this via their own targets)
pnpm exec hassan-devkit i18n:check || exit 1

# 3. The CI skeleton must match the installed devkit when it is being committed
if git diff --cached --name-only | grep -q '^\.github/workflows/ci\.yml$'; then
  pnpm exec hassan-devkit ci:doctor || exit 1
fi

# 4. Per-project lint/format on staged files (targets derived from the workspace)
pnpm exec lint-staged
